export const SYNC_TASK_OPERATION = Object.freeze({
  CREATE: 'createSyncTask',
  UPDATE: 'updateSyncTask',
  UPDATE_IGNORE_PATTERNS: 'updateSyncTaskIgnorePatterns',
  DELETE: 'deleteSyncTask',
})

export const SYNC_TASK_SAVE_PROGRESS_STEP = Object.freeze({
  SAVE: 'save',
})

export const SYNC_TASK_DELETE_PROGRESS_STEP = Object.freeze({
  DELETE: 'delete',
})

export const SYNC_TASK_OPERATION_PROGRESS_STEPS = Object.freeze({
  [SYNC_TASK_OPERATION.CREATE]: SYNC_TASK_SAVE_PROGRESS_STEP,
  [SYNC_TASK_OPERATION.UPDATE]: SYNC_TASK_SAVE_PROGRESS_STEP,
  [SYNC_TASK_OPERATION.UPDATE_IGNORE_PATTERNS]: SYNC_TASK_SAVE_PROGRESS_STEP,
  [SYNC_TASK_OPERATION.DELETE]: SYNC_TASK_DELETE_PROGRESS_STEP,
})
